@SuperHeroApi.DotNet8_HostAddress = https://localhost:7138

GET {{SuperHeroApi.DotNet8_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{SuperHeroApi.DotNet8_HostAddress}}/weatherforecast

###

GET {{SuperHeroApi.DotNet8_HostAddress}}/api/superhero

###

POST {{SuperHeroApi.DotNet8_HostAddress}}/api/superhero
Content-Type: application/json

{
  //SuperHero
}

###
